export const data = [
    {
        asset: 'LA100001',
        name: 'Laptop HP Probook 450 G1',
        assignedTo: 'Laptop',
        assignedBy: 'binhnv',
        assignedDate: '12/10/2017',
        state: 'Accepted',
    },
    {
        asset: 'MO100004',
        name: 'Laptop HP Probook 450 G1',
        assignedTo: 'Laptop',
        assignedBy: 'taipt',
        assignedDate: '12/10/2018',
        state: 'Accepted',
    },
    {
        asset: 'PC100116',
        name: 'Personal Computer',
        assignedTo: 'hoannv',
        assignedBy: 'binhnv',
        assignedDate: '12/10/2019',
        state: 'Accepted',
    },
    {
        asset: 'PC100116',
        name: 'Laptop HP Probook 450 G1',
        assignedTo: 'Laptop',
        assignedBy: 'binhnv',
        assignedDate: '12/10/2018',
        state: 'Waiting for acceptance',
    },
    {
        asset: 'PC100116',
        name: 'Laptop HP Probook 450 G1',
        assignedTo: 'Laptop',
        assignedBy: 'thinhpt',
        assignedDate: '12/10/2020',
        state: 'Accepted',
    },
    {
        asset: 'LA100001',
        name: 'Personal Computer',
        assignedTo: 'person',
        assignedBy: 'binhnv',
        assignedDate: '12/10/2018',
        state: 'Waiting for acceptance',
    },
    {
        asset: 'PC100116',
        name: 'Personal Computer',
        assignedTo: 'Laptop',
        assignedBy: 'binhnv',
        assignedDate: '12/10/2018',
        state: 'Accepted',
    },
    {
        asset: 'AB12388',
        name: 'Personal Computer',
        assignedTo: 'Laptop',
        assignedBy: 'ngocab',
        assignedDate: '12/10/2022',
        state: 'Accepted',
    },
    {
        asset: 'LA100001',
        name: 'Monitor',
        assignedTo: 'Laptop',
        assignedBy: 'zangho',
        assignedDate: '12/10/2018',
        state: 'Accepted',
    },
    {
        asset: 'LA100001',
        name: 'Laptop HP Probook 450 G1',
        assignedTo: 'Laptop',
        assignedBy: 'binhnv',
        assignedDate: '12/10/2022',
        state: 'Accepted',
    },
];
